### ISSUE TITLE
数据库名称问题

### ISSUE THREAD

**Issue by Risingrode** [XC0703/better-chat#1]
您的数据库是better-chat,我使用Mysql进行创建的时候，不支持"-",去除“-”之后才可以创建，希望可以简单修改一下数据库名称。
![image](https://github.com/XC0703/better-chat/assets/97512230/80bd96cc-7ceb-406b-ac74-3dc81bcf851b)

**Comment by Risingrode** [comment]
有没有专门的sql文件呀，进去之后，啥也没有，挺空的

**Comment by XC0703** [comment]
> 您的数据库是better-chat,我使用Mysql进行创建的时候，不支持"-",去除“-”之后才可以创建，希望可以简单修改一下数据库名称。 ![image](https://private-user-images.githubusercontent.com/97512230/328530623-80bd96cc-7ceb-406b-ac74-3dc81bcf851b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODk3MzQsIm5iZiI6MTcxNTA4OTQzNCwicGF0aCI6Ii85NzUxMjIzMC8zMjg1MzA2MjMtODBiZDk2Y2MtN2NlYi00MDZiLWFjNzQtM2RjODFiY2Y4NTFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDEzNDM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkODEzNGRhMWVjM2M3NTA1MTg2MzFlMTYyZGFiZDUyNDRhOWNkNTdhYWE0MDcwNThhODlkNDJmNGRkODI1NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nWTDvCFmAgRvqdUxB3yq4jLDMsq1vbisgBH_9gPxEOM)

这个报错是因为 MySQL 建库建表时，如果名称含有特殊字符，则需要用引号括起来：
1、如果你的 MySQL 服务器的 ANSI_QUOTES 模式是 OFF，那么你需要使用反引号来包围数据库名：CREATE DATABASE \`better-chat\`;
2、如果你的 MySQL 服务器的 ANSI_QUOTES 模式是 OFF，那么你需要使用单引号或双引号来包围数据库名：CREATE DATABASE "better-chat";
一般默认第一种情况，在 MySQL 中，通常使用反引号来包围数据库、表或列名，特别是当它们包含特殊字符或关键字时。
这里就不改了，不过可以导出一个sql文件用于增加模拟数据。

**Comment by XC0703** [comment]
> 有没有专门的sql文件呀，进去之后，啥也没有，挺空的

好的，已经上传了，建好库后可以用 source 命令或者 Navicat Premium 等工具运行项目下的 better-chat.sql 文件，方便可以在本地数据库增加一些模拟数据，同时由于静态资源存储在本地没有上传到仓库，所以需要显示的文件会呈现兜底样式，不会报错。（注意：此步可不进行，保持数据库原始空白状态。）

**Comment by Risingrode** [comment]
学到了，谢谢你
